FROM node:20-slim

WORKDIR /app

# Install OpenSSL (dibutuhkan Prisma) dan nodemon
RUN apt-get update && apt-get install -y openssl && npm install -g nodemon

COPY package*.json ./
RUN npm ci

# Salin folder prisma untuk inisialisasi Client
COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 5000

# Jalankan migration dan seed sebelum menyalakan nodemon
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && nodemon src/index.js"]
